---
sudo: false
jdk:
- oraclejdk8
language: ruby
cache: bundler
rvm:
- jruby-1.7.25
script:
- bundle exec rspec spec
matrix:
  include:
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=master
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=6.x
  - rvm: jruby-9.1.13.0
    env: LOGSTASH_BRANCH=6.0
  - rvm: jruby-1.7.27
    env: LOGSTASH_BRANCH=5.6
  fast_finish: true
